Camera:
  Focal: 13.971313932573906
  High: 650.0
Center:
  Camera_high: 670
  Center_X: 334
  Center_Y: 256
  Front: 88
  Horizon: 188
  Inner: 44
  Outer: 280
  X: 308
  Y: 266
FPS: 20
HSV:
  Ball:
  - 0
  - 34
  - 27
  - 100
  - 28
  - 100
  Blue:
  - 213
  - 258
  - 70
  - 97
  - 39
  - 100
  Green:
  - 113
  - 208
  - 21
  - 70
  - 31
  - 91
  White:
  - 0
  - 360
  - 0
  - 27
  - 0
  - 31
  Yellow:
  - 30
  - 109
  - 0
  - 98
  - 57
  - 100
  black:
    angle: 20
    gray: 57
  white:
    angle: 3
    gray: 172
Parameterbutton: 4
SCAN:
  Angle_Near_Gap: 4
  Angle_range_1: 2
  Angle_range_2_3: 3
  Dont_Search_Angle_1: 31
  Dont_Search_Angle_2: 150
  Dont_Search_Angle_3: 267
  Magn_Far_End: 238
  Magn_Far_Start: 141
  Magn_Middle_Start: 93
  Magn_Near_Gap: 3
  Magn_Near_Start: 43
blackItem:
  angle: 3
  gray: 40
whiteline:
  angle: 4
  gray: 100
