FIRA:
  Camera: {Focal: 13.971313932573906, High: 650.0}
  Center: {Camera_high: 650, Center_X: 275, Center_Y: 270, Front: 267, Inner: 44,
    Outer: 235, X: 308, Y: 266}
  FPS: 20
  HSV:
    Ball: [0, 55, 35, 100, 42, 100]
    Blue: [160, 261, 0, 100, 0, 100]
    Bluerange: [245, 204, 255, 179, 255, 72]
    Green: [0, 195, 59, 100, 18, 100]
    Greenrange: [188, 114, 255, 130, 255, 0]
    Redrange: [36, 0, 255, 118, 255, 0]
    White: [0, 359, 0, 30, 0, 30]
    Whiterange: [227, 146, 166, 13, 255, 134]
    Yellow: [33, 107, 20, 85, 54, 100]
    Yellowrange: [103, 59, 255, 70, 255, 137]
    black: {angle: 1, gray: 31}
    white: {angle: 1, gray: 170}
  SCAN: {Angle_Near_Gap: 4, Angle_range_1: 1, Angle_range_2_3: 1, Dont_Search_Angle_1: 329,
    Dont_Search_Angle_2: 93, Dont_Search_Angle_3: 210, Magn_Far_End: 240, Magn_Far_Start: 141,
    Magn_Middle_Start: 98, Magn_Near_Gap: 4, Magn_Near_Start: 40}
